import { Manuscript, BlogPost, GuestbookEntry } from './types';

export const SAMPLE_MANUSCRIPTS: Manuscript[] = [
  {
    id: '1',
    inputer: 'Punky S.',
    kode_inventarisasi: 'TPPKP.02.1',
    judul_dari_tim: 'شرح عومل الجرجاني',
    afiliasi: 'Nahdlatut Turats',
    nama_koleksi: 'NDALEM',
    nomor_koleksi: '02.001.1',
    judul_dari_afiliasi: 'Syarhul Amil',
    nomor_digitalisasi: 'NT.001',
    url_konten: 'https://images.unsplash.com/photo-1544640808-32ca72ac7f67?auto=format&fit=crop&q=80&w=1200',
    deskripsi_umum: 'Menjelaskan tentang gramatika bahasa arab. Diawali dengan pembahasan mengenai Rofa\', Nashob, Jer. Termasuk i\'rab.',
    kategori_ilmu_pesantren: 'NAHWU',
    klasifikasi_kailani: 'Ilm Al-Lughah',
    pengarang: 'Asy-Syekh Abdurrahman',
    penyalin: 'Ibnu Zaidan',
    tahun_penulisan_di_teks: '1244 H',
    konversi_masehi: '1828 M',
    lokasi_penyalinan: 'Gresik',
    asal_usul_naskah: 'Peninggalan KH. Qomaruddin',
    bahasa: 'Jawa, Arab',
    aksara: 'Arab, Pego',
    kover: 'Kulit Hewan',
    ukuran_kover: '21 x 15 cm',
    jilid: 'Manul',
    ukuran_kertas: '19 x 13 cm',
    ukuran_dimensi: 'Folio kecil',
    watermark: 'Pro Patria',
    countermark: 'Van Galder',
    tinta: 'Hitam & Merah (Bata)',
    jumlah_halaman: 62,
    halaman_kosong: 2,
    jumlah_baris_per_halaman: 11,
    rubrikasi: 'Terdapat judul bab berwarna merah',
    iluminasi: 'Sederhana pada halaman awal',
    ilustrasi: 'Tidak ada',
    catatan_pinggir: 'Sangat padat',
    catatan_makna: 'Makna gandul khas pesantren',
    kolofon: 'Selesai pada hari Jumat wage',
    catatan_marginal: 'Terdapat catatan doa di akhir',
    kondisi_fisik_naskah: 'Sangat bagus',
    keterbacaan: 'Bisa Dibaca Jelas',
    kelengkapan_naskah: 'Lengkap',
    catatan_catatan: 'Naskah ini sangat penting untuk sejarah pengajaran Nahwu di Jawa Timur.',
    kata_kunci: 'Nahwu, Syarah, Amil, Qomaruddin',
    glosarium: 'Amil: Kata yang mempengaruhi akhir kalimat',
    referensi: 'Katalog Nahdlatut Turats Vol 1',
    manuskrip_terkait: 'TPPKP.02.2',
    tokoh_terkait: 'Sultan Agung',
    jenis_kertas: 'Daluang',
    url_kover: 'https://images.unsplash.com/photo-1544640808-32ca72ac7f67?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    kode_inventarisasi: 'TPPKP.02.2',
    judul_dari_tim: '??? ????????',
    afiliasi: 'Nahdlatut Turats',
    nama_koleksi: 'NDALEM',
    nomor_koleksi: '02.001.2',
    judul_dari_afiliasi: 'Syarhul Jurmiyah',
    nomor_digitalisasi: 'NT.002',
    deskripsi_umum: 'Memberikan penjelasan kitab jurumiyah',
    kategori_ilmu_pesantren: 'NAHWU',
    bahasa: 'Jawa, Arab',
    aksara: 'Arab, Pego',
    jumlah_halaman: 104,
    kondisi_fisik_naskah: 'Sangat bagus',
    keterbacaan: 'Bisa Dibaca Jelas',
    kelengkapan_naskah: 'Lengkap',
    url_kover: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    kode_inventarisasi: 'TPPKP.02.4',
    judul_dari_tim: '????? ???????',
    afiliasi: 'Nahdlatut Turats',
    nama_koleksi: 'NDALEM',
    nomor_koleksi: '02.002.1',
    judul_dari_afiliasi: 'Wiqayatul Abrar',
    nomor_digitalisasi: 'NT.004',
    deskripsi_umum: 'Terdapat 5 bab tentang hak-hak bagi suami dan istri.',
    kategori_ilmu_pesantren: 'FIKIH NIKAH',
    konversi_masehi: '1 November 1861 M',
    bahasa: 'Jawa, Arab',
    aksara: 'Arab, Pego',
    jumlah_halaman: 29,
    kondisi_fisik_naskah: 'Sangat bagus',
    keterbacaan: 'Bisa Dibaca Jelas',
    kelengkapan_naskah: 'Lengkap',
    url_kover: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=800',
  },
];

export const SAMPLE_BLOGS: BlogPost[] = [
  {
    id: '1',
    title: 'Pentingnya Pelestarian Manuskrip Nusantara',
    excerpt: 'Manuskrip Nusantara adalah jendela bagi kita untuk melihat masa lalu, budaya, dan kearifan lokal yang telah ada sejak berabad-abad yang lalu.',
    content: 'Manuskrip Nusantara adalah jendela bagi kita untuk melihat masa lalu, budaya, dan kearifan lokal yang telah ada sejak berabad-abad yang lalu. Dalam Galeri Manuskrip Sampurnan, kami berupaya mendigitalisasi setiap halaman untuk memastikan pengetahuan ini tidak hilang ditelan zaman.',
    author: 'Admin',
    date: '2024-03-15T10:00:00Z',
    image_url: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    title: 'Mengenal Aksara Pego dalam Tradisi Pesantren',
    excerpt: 'Aksara Pego merupakan adaptasi abjad Arab untuk menuliskan bahasa Jawa, Sunda, atau Madura.',
    content: 'Aksara Pego merupakan adaptasi abjad Arab untuk menuliskan bahasa Jawa, Sunda, atau Madura. Penggunaannya sangat luas di lingkungan pesantren, terutama untuk memberikan makna pada naskah-naskah keislaman klasik.',
    author: 'Kurator',
    date: '2024-03-20T14:30:00Z',
    image_url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800',
  }
];

export const SAMPLE_GUESTBOOK: GuestbookEntry[] = [
  {
    id: '1',
    name: 'Ahmad Fauzi',
    message: 'Sangat mengapresiasi upaya digitalisasi manuskrip ini. Sangat membantu penelitian saya.',
    date: '2024-04-01T08:00:00Z',
  },
  {
    id: '2',
    name: 'Siti Aminah',
    message: 'Visualisasi webnya sangat bagus dan mudah digunakan. Terus berkarya!',
    date: '2024-04-05T09:15:00Z',
  }
];
